// Polski kalendarz imienin. Klucz "MM-DD" → lista imion obchodzonych danego dnia.
// Zbiór obejmuje najpopularniejsze imieniny; można rozszerzać.

const NAME_DAYS: Record<string, string[]> = {
  "01-01": ["Mieszko", "Mieczysław", "Maria"],
  "01-02": ["Bazyli", "Grzegorz", "Izydor"],
  "01-03": ["Arletta", "Danuta", "Genowefa"],
  "01-04": ["Anielika", "Eugeniusz", "Tytus"],
  "01-05": ["Edward", "Hanna", "Szymon"],
  "01-06": ["Kacper", "Melchior", "Baltazar"],
  "01-07": ["Julian", "Lucjan", "Rajmund"],
  "01-08": ["Seweryn", "Mścisław", "Teofil"],
  "01-09": ["Adrian", "Antoni", "Julian"],
  "01-10": ["Dobrosław", "Jan", "Wilhelm"],
  "01-11": ["Honorata", "Matylda", "Teodozjusz"],
  "01-12": ["Arkadiusz", "Benedykt", "Czesław"],
  "01-13": ["Bogumił", "Weronika", "Hilary"],
  "01-14": ["Feliks", "Nina", "Domosław"],
  "01-15": ["Aleksander", "Arnold", "Paweł"],
  "01-16": ["Marceli", "Włodzimierz", "Waldemar"],
  "01-17": ["Antoni", "Jan", "Rościsław"],
  "01-18": ["Piotr", "Małgorzata", "Bogumiła"],
  "01-19": ["Henryk", "Marta", "Mariusz"],
  "01-20": ["Fabian", "Sebastian", "Dobiegniew"],
  "01-21": ["Agnieszka", "Jarosław", "Inez"],
  "01-22": ["Anastazy", "Wincenty", "Wiktor"],
  "01-23": ["Ildefons", "Rajmund", "Maria"],
  "01-24": ["Felicja", "Rafał", "Franciszek"],
  "01-25": ["Paweł", "Miłosz", "Elwira"],
  "01-26": ["Tymoteusz", "Tytus", "Paula"],
  "01-27": ["Aniela", "Anioł", "Przybysław"],
  "01-28": ["Radomir", "Tomasz", "Walery"],
  "01-29": ["Zdzisław", "Franciszek", "Józef"],
  "01-30": ["Martyna", "Maciej", "Hiacynta"],
  "01-31": ["Jan", "Marcela", "Ludwika"],

  "02-01": ["Brygida", "Ignacy", "Seweryn"],
  "02-02": ["Maria", "Miłosława", "Halszka"],
  "02-03": ["Błażej", "Oskar", "Telimena"],
  "02-04": ["Andrzej", "Weronika", "Joanna"],
  "02-05": ["Agata", "Adelajda", "Dobromił"],
  "02-06": ["Dorota", "Paweł", "Amanda"],
  "02-07": ["Ryszard", "Teodor", "Sulisław"],
  "02-08": ["Hieronim", "Sebastian", "Jan"],
  "02-09": ["Apolonia", "Cyryl", "Eryk"],
  "02-10": ["Elwira", "Jacek", "Scholastyka"],
  "02-11": ["Grzegorz", "Lucjan", "Olgierd"],
  "02-12": ["Eulalia", "Damian", "Radosław"],
  "02-13": ["Grzegorz", "Katarzyna", "Jordan"],
  "02-14": ["Walenty", "Cyryl", "Metody"],
  "02-15": ["Faustyn", "Jowita", "Zygfryd"],
  "02-16": ["Danuta", "Julianna", "Daniel"],
  "02-17": ["Aleksy", "Donat", "Zbigniew"],
  "02-18": ["Symeon", "Konstancja", "Flawian"],
  "02-19": ["Arnold", "Konrad", "Marceli"],
  "02-20": ["Leon", "Ludomir", "Eucheriusz"],
  "02-21": ["Eleonora", "Feliks", "Robert"],
  "02-22": ["Marta", "Małgorzata", "Piotr"],
  "02-23": ["Roman", "Damian", "Izabela"],
  "02-24": ["Maciej", "Bogusz", "Sergiusz"],
  "02-25": ["Wiktor", "Cezary", "Donat"],
  "02-26": ["Aleksander", "Mirosław", "Bogumił"],
  "02-27": ["Gabriel", "Anastazja", "Leander"],
  "02-28": ["Roman", "Ludomir", "Makary"],
  "02-29": ["Lech", "Roman", "Antonina"],

  "03-01": ["Albin", "Antonina", "Radosław"],
  "03-02": ["Halszka", "Helena", "Paweł"],
  "03-03": ["Kunegunda", "Maryna", "Tycjan"],
  "03-04": ["Kazimierz", "Łucja", "Eugeniusz"],
  "03-05": ["Adrian", "Fryderyk", "Oliwia"],
  "03-06": ["Róża", "Wiktor", "Koleta"],
  "03-07": ["Tomasz", "Perpetua", "Felicyta"],
  "03-08": ["Beata", "Wincenty", "Jan"],
  "03-09": ["Franciszka", "Dominik", "Katarzyna"],
  "03-10": ["Cyprian", "Aleksander", "Marceli"],
  "03-11": ["Konstanty", "Benedykt", "Sofroniusz"],
  "03-12": ["Grzegorz", "Alojzy", "Bernard"],
  "03-13": ["Bożena", "Krystyna", "Patrycja"],
  "03-14": ["Matylda", "Leon", "Łazarz"],
  "03-15": ["Klemens", "Ludwika", "Longin"],
  "03-16": ["Izabela", "Hilary", "Oktawia"],
  "03-17": ["Patryk", "Zbigniew", "Gertruda"],
  "03-18": ["Cyryl", "Edward", "Boguchwał"],
  "03-19": ["Józef", "Bogdan", "Aleksandryna"],
  "03-20": ["Klaudia", "Maurycy", "Aleksandra"],
  "03-21": ["Benedykt", "Lubomira", "Mikołaj"],
  "03-22": ["Katarzyna", "Bogusław", "Paweł"],
  "03-23": ["Pelagia", "Feliks", "Oktawian"],
  "03-24": ["Marek", "Gabriel", "Katarzyna"],
  "03-25": ["Maria", "Wieńczysław", "Ireneusz"],
  "03-26": ["Larysa", "Emanuel", "Teodor"],
  "03-27": ["Lidia", "Ernest", "Rupert"],
  "03-28": ["Aniela", "Jan", "Sykstus"],
  "03-29": ["Wiktoryna", "Eustachy", "Cyryl"],
  "03-30": ["Amelia", "Kwiryn", "Jan"],
  "03-31": ["Beniamin", "Kornelia", "Balbina"],

  "04-01": ["Grażyna", "Hugo", "Teodora"],
  "04-02": ["Franciszek", "Władysław", "Urban"],
  "04-03": ["Ryszard", "Pankracy", "Ryszarda"],
  "04-04": ["Izydor", "Wacław", "Benedykt"],
  "04-05": ["Wincenty", "Irena", "Katarzyna"],
  "04-06": ["Celestyn", "Ireneusz", "Wilhelm"],
  "04-07": ["Rufin", "Herman", "Donat"],
  "04-08": ["Dionizy", "January", "Radosław"],
  "04-09": ["Marceli", "Maria", "Dobrosława"],
  "04-10": ["Michał", "Makary", "Daniel"],
  "04-11": ["Leon", "Filip", "Jaromir"],
  "04-12": ["Juliusz", "Lubosław", "Wiktor"],
  "04-13": ["Przemysław", "Marcin", "Ida"],
  "04-14": ["Justyna", "Bereniki", "Waleriana"],
  "04-15": ["Anastazja", "Wacław", "Ludwina"],
  "04-16": ["Cecylian", "Benedykt", "Erwina"],
  "04-17": ["Rudolf", "Robert", "Aniceta"],
  "04-18": ["Bogusława", "Apoloniusz", "Bogumił"],
  "04-19": ["Adolf", "Tymon", "Leon"],
  "04-20": ["Czesław", "Agnieszka", "Teodor"],
  "04-21": ["Anzelm", "Bartosz", "Feliks"],
  "04-22": ["Kaja", "Leonia", "Łukasz"],
  "04-23": ["Wojciech", "Jerzy", "Gerard"],
  "04-24": ["Aleksander", "Grzegorz", "Fides"],
  "04-25": ["Marek", "Jarosław", "Wasyl"],
  "04-26": ["Marzena", "Maria", "Klet"],
  "04-27": ["Zyta", "Teofil", "Felicja"],
  "04-28": ["Paweł", "Piotr", "Waleria"],
  "04-29": ["Piotr", "Katarzyna", "Robert"],
  "04-30": ["Marian", "Katarzyna", "Donat"],

  "05-01": ["Józef", "Jeremiasz", "Filip"],
  "05-02": ["Zygmunt", "Atanazy", "Longina"],
  "05-03": ["Maria", "Antonina", "Jakub"],
  "05-04": ["Monika", "Florian", "Waleria"],
  "05-05": ["Irena", "Waldemar", "Angelika"],
  "05-06": ["Filip", "Jakub", "Judyta"],
  "05-07": ["Ludmiła", "Gizela", "Benedykt"],
  "05-08": ["Stanisław", "Wiktor", "Liza"],
  "05-09": ["Grzegorz", "Bożydar", "Karolina"],
  "05-10": ["Antonin", "Izydor", "Symeon"],
  "05-11": ["Igancy", "Mira", "Filip"],
  "05-12": ["Pankracy", "Dominik", "Achilles"],
  "05-13": ["Serwacy", "Robert", "Gliceria"],
  "05-14": ["Bonifacy", "Maciej", "Dobiesław"],
  "05-15": ["Zofia", "Nadzieja", "Izydor"],
  "05-16": ["Andrzej", "Szymon", "Jędrzej"],
  "05-17": ["Weronika", "Sławomir", "Paschalis"],
  "05-18": ["Eryk", "Feliks", "Jan"],
  "05-19": ["Piotr", "Celestyn", "Iwo"],
  "05-20": ["Bernardyn", "Bazyli", "Aleksander"],
  "05-21": ["Wiktor", "Tymoteusz", "Kryspin"],
  "05-22": ["Helena", "Wiesława", "Julia"],
  "05-23": ["Iwona", "Dezyderiusz", "Michał"],
  "05-24": ["Joanna", "Zuzanna", "Marika"],
  "05-25": ["Grzegorz", "Magda", "Urban"],
  "05-26": ["Filip", "Paulina", "Ewelina"],
  "05-27": ["Magdalena", "Jan", "Juliusz"],
  "05-28": ["Jaromir", "August", "Wilhelm"],
  "05-29": ["Magdalena", "Bogusława", "Urszula"],
  "05-30": ["Ferdynand", "Karol", "Joanna"],
  "05-31": ["Aniela", "Petronela", "Kamila"],

  "06-01": ["Jakub", "Konrad", "Justyn"],
  "06-02": ["Marianna", "Erazm", "Marcelin"],
  "06-03": ["Leszek", "Karol", "Klotylda"],
  "06-04": ["Kwiryna", "Franciszek", "Optat"],
  "06-05": ["Bonifacy", "Waleria", "Walter"],
  "06-06": ["Norbert", "Laura", "Paulina"],
  "06-07": ["Robert", "Wiesław", "Ariadna"],
  "06-08": ["Medard", "Maksym", "Seweryn"],
  "06-09": ["Efrem", "Pelagia", "Felicjan"],
  "06-10": ["Bogumił", "Małgorzata", "Diana"],
  "06-11": ["Barnaba", "Radomił", "Feliks"],
  "06-12": ["Janina", "Onufry", "Leon"],
  "06-13": ["Antoni", "Lucjan", "Gerard"],
  "06-14": ["Bazyli", "Eliza", "Walerian"],
  "06-15": ["Wit", "Jolanta", "Wioleta"],
  "06-16": ["Alina", "Justyna", "Benon"],
  "06-17": ["Laura", "Marcjan", "Albert"],
  "06-18": ["Marek", "Elżbieta", "Gerwazy"],
  "06-19": ["Gerwazy", "Protazy", "Julianna"],
  "06-20": ["Bogna", "Florentyna", "Rafał"],
  "06-21": ["Alojzy", "Alicja", "Rudolf"],
  "06-22": ["Paulina", "Jan", "Tomasz"],
  "06-23": ["Wanda", "Zenon", "Józef"],
  "06-24": ["Jan", "Danuta", "Bartłomiej"],
  "06-25": ["Wilhelm", "Łucja", "Dorota"],
  "06-26": ["Jan", "Paweł", "Rudolfina"],
  "06-27": ["Maria", "Władysław", "Cyryl"],
  "06-28": ["Leon", "Ireneusz", "Florentyna"],
  "06-29": ["Piotr", "Paweł", "Salomea"],
  "06-30": ["Emilia", "Lucyna", "Arnold"],

  "07-01": ["Halina", "Marian", "Teodoryk"],
  "07-02": ["Urban", "Jagoda", "Maria"],
  "07-03": ["Anatol", "Tomasz", "Jacek"],
  "07-04": ["Malwina", "Teodor", "Elżbieta"],
  "07-05": ["Antoni", "Karolina", "Maria"],
  "07-06": ["Dominika", "Gotard", "Łucja"],
  "07-07": ["Estera", "Cyryl", "Metody"],
  "07-08": ["Elżbieta", "Eugeniusz", "Edgar"],
  "07-09": ["Weronika", "Zenon", "Lukrecja"],
  "07-10": ["Filip", "Antoni", "Amelia"],
  "07-11": ["Benedykt", "Olga", "Kalist"],
  "07-12": ["Brunon", "Jan", "Wera"],
  "07-13": ["Andrzej", "Małgorzata", "Ernest"],
  "07-14": ["Kamil", "Bonawentura", "Ulryk"],
  "07-15": ["Henryk", "Włodzimierz", "Dawid"],
  "07-16": ["Maria", "Stefan", "Eustachy"],
  "07-17": ["Aleksy", "Bogdan", "Marcelina"],
  "07-18": ["Kamil", "Szymon", "Robert"],
  "07-19": ["Wincenty", "Wodzisław", "Alfred"],
  "07-20": ["Czesław", "Hieronim", "Małgorzata"],
  "07-21": ["Daniel", "Wawrzyniec", "Andrzej"],
  "07-22": ["Maria", "Magdalena", "Bolesława"],
  "07-23": ["Bogna", "Brygida", "Apolinary"],
  "07-24": ["Kinga", "Krystyna", "Olga"],
  "07-25": ["Jakub", "Krzysztof", "Walentyna"],
  "07-26": ["Anna", "Joachim", "Mirosława"],
  "07-27": ["Natalia", "Julia", "Aurelian"],
  "07-28": ["Wiktor", "Innocenty", "Aida"],
  "07-29": ["Marta", "Olaf", "Ludmiła"],
  "07-30": ["Julita", "Piotr", "Aldona"],
  "07-31": ["Ignacy", "Helena", "Lubomir"],

  "08-01": ["Alfons", "Nadia", "Piotr"],
  "08-02": ["Gustaw", "Kamila", "Alfons"],
  "08-03": ["Lidia", "August", "Nikodem"],
  "08-04": ["Dominik", "Jan", "Protazy"],
  "08-05": ["Maria", "Oswald", "Emil"],
  "08-06": ["Sława", "Jakub", "Oktawian"],
  "08-07": ["Kajetan", "Doryta", "Sykstus"],
  "08-08": ["Cyryl", "Dominik", "Emilian"],
  "08-09": ["Roman", "Ryszard", "Klara"],
  "08-10": ["Wawrzyniec", "Borys", "Filomena"],
  "08-11": ["Zuzanna", "Klara", "Włodzimierz"],
  "08-12": ["Klara", "Lech", "Innocenty"],
  "08-13": ["Diana", "Hipolit", "Radomir"],
  "08-14": ["Maksymilian", "Alfred", "Euzebiusz"],
  "08-15": ["Maria", "Napoleon", "Stella"],
  "08-16": ["Roch", "Stefan", "Joachim"],
  "08-17": ["Jacek", "Julianna", "Anita"],
  "08-18": ["Helena", "Bronisław", "Bogusław"],
  "08-19": ["Jan", "Bolesław", "Ludwik"],
  "08-20": ["Bernard", "Sobiesław", "Samuel"],
  "08-21": ["Joanna", "Kazimiera", "Pius"],
  "08-22": ["Cezary", "Zygfryd", "Maria"],
  "08-23": ["Apolinary", "Filip", "Róża"],
  "08-24": ["Bartłomiej", "Jerzy", "Emilia"],
  "08-25": ["Ludwik", "Józef", "Luiza"],
  "08-26": ["Maria", "Zefiryn", "Aleksander"],
  "08-27": ["Monika", "Cezary", "Józef"],
  "08-28": ["Augustyn", "Patrycja", "Wyszomir"],
  "08-29": ["Jan", "Sabina", "Beata"],
  "08-30": ["Róża", "Feliks", "Szczęsny"],
  "08-31": ["Rajmund", "Bohdan", "Paulina"],

  "09-01": ["Bronisław", "Idzi", "Bronisława"],
  "09-02": ["Stefan", "Wilhelm", "Julian"],
  "09-03": ["Grzegorz", "Szymon", "Izabela"],
  "09-04": ["Rozalia", "Ida", "Justyna"],
  "09-05": ["Wawrzyniec", "Dorota", "Teodor"],
  "09-06": ["Beata", "Eugeniusz", "Zachariasz"],
  "09-07": ["Regina", "Melchior", "Domosława"],
  "09-08": ["Maria", "Adrianna", "Radosław"],
  "09-09": ["Piotr", "Sergiusz", "Ścibor"],
  "09-10": ["Mikołaj", "Łukasz", "Aldona"],
  "09-11": ["Prot", "Jacek", "Dagny"],
  "09-12": ["Gwidon", "Maria", "Radzimir"],
  "09-13": ["Eugenia", "Jan", "Aureliusz"],
  "09-14": ["Roksana", "Bernard", "Cyprian"],
  "09-15": ["Albin", "Nikodem", "Rolanda"],
  "09-16": ["Edyta", "Kornel", "Cyprian"],
  "09-17": ["Franciszek", "Robert", "Justyn"],
  "09-18": ["Stanisław", "Irena", "Józef"],
  "09-19": ["Konstancja", "January", "Teodor"],
  "09-20": ["Filipina", "Eustachy", "Renata"],
  "09-21": ["Mateusz", "Jonasz", "Hipolit"],
  "09-22": ["Maurycy", "Tomasz", "Joachim"],
  "09-23": ["Bogusław", "Tekla", "Linus"],
  "09-24": ["Gerard", "Teodor", "Dora"],
  "09-25": ["Aurelia", "Władysław", "Kleofas"],
  "09-26": ["Kosma", "Damian", "Justyna"],
  "09-27": ["Wincenty", "Damian", "Mirabela"],
  "09-28": ["Wacław", "Marek", "Salomon"],
  "09-29": ["Michał", "Michalina", "Gabriel"],
  "09-30": ["Wera", "Honoriusz", "Hieronim"],

  "10-01": ["Danuta", "Remigiusz", "Teresa"],
  "10-02": ["Teofil", "Dionizy", "Sławomir"],
  "10-03": ["Teresa", "Gerard", "Jan"],
  "10-04": ["Franciszek", "Rozalia", "Edwin"],
  "10-05": ["Placyd", "Apolinary", "Faustyna"],
  "10-06": ["Artur", "Brunon", "Fryderyka"],
  "10-07": ["Marek", "Mirella", "Justyna"],
  "10-08": ["Pelagia", "Brygida", "Walter"],
  "10-09": ["Wincenty", "Ludwik", "Dionizy"],
  "10-10": ["Leon", "Paulina", "Daniel"],
  "10-11": ["Aldona", "Emil", "Dobromira"],
  "10-12": ["Edwin", "Maksymilian", "Rajmund"],
  "10-13": ["Edward", "Gerald", "Mikołaj"],
  "10-14": ["Alan", "Bernard", "Kalikst"],
  "10-15": ["Teresa", "Jadwiga", "Florentyna"],
  "10-16": ["Gaweł", "Aurelia", "Ambroży"],
  "10-17": ["Wiktor", "Ignacy", "Małgorzata"],
  "10-18": ["Łukasz", "Julian", "Bratumił"],
  "10-19": ["Piotr", "Ziemowit", "Jan"],
  "10-20": ["Ireneusz", "Jan", "Witalis"],
  "10-21": ["Urszula", "Hilary", "Celina"],
  "10-22": ["Halka", "Filip", "Salomea"],
  "10-23": ["Marleny", "Seweryn", "Igancy"],
  "10-24": ["Rafał", "Marcin", "Antoni"],
  "10-25": ["Bonifacy", "Daria", "Wilhelmina"],
  "10-26": ["Ewaryst", "Lucjan", "Damian"],
  "10-27": ["Iwona", "Sabina", "Wincenty"],
  "10-28": ["Szymon", "Juda", "Tadeusz"],
  "10-29": ["Euzebia", "Wioletta", "Narcyz"],
  "10-30": ["Zenobia", "Edmund", "Przemysław"],
  "10-31": ["Urban", "Saturnin", "Krzysztof"],

  "11-01": ["Wszystkich Świętych", "Bogdan", "Seweryna"],
  "11-02": ["Bożydar", "Tobiasz", "Bohdan"],
  "11-03": ["Sylwia", "Hubert", "Marcin"],
  "11-04": ["Karol", "Olgierd", "Emeryk"],
  "11-05": ["Sławomir", "Elżbieta", "Zachariasz"],
  "11-06": ["Feliks", "Leonard", "Ziemowit"],
  "11-07": ["Antoni", "Ernest", "Florenty"],
  "11-08": ["Sewer", "Gotfryd", "Klaudiusz"],
  "11-09": ["Ludwik", "Teodor", "Ursyn"],
  "11-10": ["Ludomir", "Lena", "Andrzej"],
  "11-11": ["Marcin", "Bartłomiej", "Teodor"],
  "11-12": ["Renata", "Witold", "Krystyn"],
  "11-13": ["Mikołaj", "Stanisław", "Benedykt"],
  "11-14": ["Roger", "Serafin", "Wawrzyniec"],
  "11-15": ["Albert", "Leopold", "Amadeusz"],
  "11-16": ["Gertruda", "Edmund", "Maria"],
  "11-17": ["Grzegorz", "Salomea", "Elżbieta"],
  "11-18": ["Roman", "Klaudyna", "Karolina"],
  "11-19": ["Elżbieta", "Seweryn", "Paweł"],
  "11-20": ["Rafał", "Feliks", "Edmund"],
  "11-21": ["Janusz", "Konrad", "Maria"],
  "11-22": ["Cecylia", "Marek", "Wszemił"],
  "11-23": ["Klemens", "Adela", "Felicyta"],
  "11-24": ["Flora", "Jan", "Chryzogon"],
  "11-25": ["Katarzyna", "Erazm", "Klemens"],
  "11-26": ["Konrad", "Leonard", "Sylwester"],
  "11-27": ["Walery", "Wirgiliusz", "Maksym"],
  "11-28": ["Zdzisław", "Lesław", "Jakub"],
  "11-29": ["Błażej", "Saturnin", "Fryderyk"],
  "11-30": ["Andrzej", "Konstanty", "Justyna"],

  "12-01": ["Natalia", "Eligiusz", "Blanka"],
  "12-02": ["Balbina", "Bibiana", "Paulina"],
  "12-03": ["Franciszek", "Ksawery", "Kasjan"],
  "12-04": ["Barbara", "Jan", "Krystian"],
  "12-05": ["Saba", "Kryspin", "Norbert"],
  "12-06": ["Mikołaj", "Jarema", "Emilian"],
  "12-07": ["Ambroży", "Marcin", "Teodor"],
  "12-08": ["Maria", "Światozar", "Makary"],
  "12-09": ["Wiesław", "Leokadia", "Joachim"],
  "12-10": ["Julia", "Judyta", "Daniel"],
  "12-11": ["Damazy", "Waldemar", "Daniel"],
  "12-12": ["Aleksandra", "Dagmara", "Joanna"],
  "12-13": ["Łucja", "Otylia", "Włodzisław"],
  "12-14": ["Alfred", "Izydor", "Jan"],
  "12-15": ["Nina", "Celina", "Waleriana"],
  "12-16": ["Zdzisława", "Albina", "Adelajda"],
  "12-17": ["Olimpia", "Łazarz", "Florian"],
  "12-18": ["Gracjan", "Bogusław", "Laurencja"],
  "12-19": ["Gabriela", "Dariusz", "Urban"],
  "12-20": ["Bogumiła", "Dominik", "Teofil"],
  "12-21": ["Tomasz", "Piotr", "Seweryn"],
  "12-22": ["Zenon", "Honorata", "Franciszka"],
  "12-23": ["Wiktoria", "Sława", "Jan"],
  "12-24": ["Adam", "Ewa", "Emilian"],
  "12-25": ["Anastazja", "Eugenia", "Piotr"],
  "12-26": ["Szczepan", "Dionizy", "Stefan"],
  "12-27": ["Jan", "Żaneta", "Maksym"],
  "12-28": ["Teofila", "Cezary", "Antoni"],
  "12-29": ["Dawid", "Tomasz", "Dominik"],
  "12-30": ["Eugeniusz", "Irmina", "Rajner"],
  "12-31": ["Sylwester", "Melania", "Kornelia"],
};

function pad(n: number) {
  return n.toString().padStart(2, "0");
}

export function getNameDays(month0: number, day: number): string[] {
  return NAME_DAYS[`${pad(month0 + 1)}-${pad(day)}`] ?? [];
}

/** Slug imienia (małe litery, polskie znaki zamienione) do URL-a. */
export function nameToSlug(name: string): string {
  return name
    .toLowerCase()
    .replaceAll("ą", "a")
    .replaceAll("ć", "c")
    .replaceAll("ę", "e")
    .replaceAll("ł", "l")
    .replaceAll("ń", "n")
    .replaceAll("ó", "o")
    .replaceAll("ś", "s")
    .replaceAll("ż", "z")
    .replaceAll("ź", "z")
    .replaceAll(" ", "-");
}

type NameDateEntry = { name: string; slug: string; month0: number; day: number };

let reverseCache: Map<string, NameDateEntry[]> | null = null;

function buildReverse(): Map<string, NameDateEntry[]> {
  if (reverseCache) return reverseCache;
  const map = new Map<string, NameDateEntry[]>();
  for (const [key, names] of Object.entries(NAME_DAYS)) {
    const [m, d] = key.split("-").map(Number);
    for (const name of names) {
      const slug = nameToSlug(name);
      const entry: NameDateEntry = { name, slug, month0: m - 1, day: d };
      const arr = map.get(slug) ?? [];
      arr.push(entry);
      map.set(slug, arr);
    }
  }
  reverseCache = map;
  return map;
}

/** Wszystkie unikalne imiona (posortowane) z ich slugami. */
export function getAllNames(): { name: string; slug: string }[] {
  const map = buildReverse();
  const out: { name: string; slug: string }[] = [];
  for (const [slug, entries] of map) out.push({ name: entries[0].name, slug });
  return out.sort((a, b) => a.name.localeCompare(b.name, "pl"));
}

/** Daty imienin dla danego sluga imienia. */
export function getDatesForSlug(slug: string): NameDateEntry[] {
  return buildReverse().get(slug) ?? [];
}

export default NAME_DAYS;
